### Requirements

In [8]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
from scipy import stats

### Reading data

column __type_of_affiliation__: type of affiliation: 1 = private, 2 = public, 3 = mixed<br>

In [18]:
data = pd.read_csv('./07-Quynh/official.csv')
type_of_affiliation = [1, 3, 1, 1, 2, 2, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1]
affli_data = pd.Series(type_of_affiliation)
data['Affiliation'] = affli_data.values
data

,Name,Rank,Likes,Retweets,Retweets to Likes,Year founded,Age,Affiliation
0,"Mayo Clinic, Rochester, Minnesota",1,96462,53265,0.552186,1889,129,1
1,Cleveland Clinic,2,229643,99463,0.433120,1921,97,3
2,"Johns Hopkins Hospital, Baltimore",3,499563,140685,0.281616,1889,129,1
3,"Massachusetts General Hospital, Boston",4,1357793,545969,0.402100,1811,207,1
4,"UCSF medical Center, San Francisco",5,24932,12247,0.491216,1864,154,2
5,University of Michigan Hospitals and Health Ce...,6,88245,30637,0.347181,1850,168,2
6,"Ronald Reagan UCLA Medical Centr, Los Angeles",7,0,0,0.000000,1955,63,2
7,"New York-Presbyterian Hospital, New York",8,18647,5091,0.273020,1868,150,1
8,"Stanford Health Care-Stanford Hospital, Stanfo...",9,188363,91690,0.486773,1959,59,1
9,Hospitals of the Unversity of Pennsylvania-Pen...,10,176139,74651,0.423819,1871,147,1
10,"Cedars-Sinai Medical Center, LA",11,0,0,0.000000,1902,116,3
11,"Barnes-Jewish Hospital, ST. Louis",12,412,186,0.451456,1902,116,1
12,"Northwestern Memorial Hospital, Chicago",13,17728,6289,0.354750,1972,46,1
13,"UPMC Presbyterian Shadyside, Pittsburgh",14,68906,28328,0.411111,1893,125,1
14,"University of Colorado Hospital, Aurora",15,749,321,0.428571,1921,97,2
15,"Thomas Jefferson University Hospitals, Philade...",16,31931,16154,0.505903,1825,193,1
16,"Duke University Hospital, Durham, North Carolina",17,25847,6636,0.256742,1838,180,1
17,"Mount Sinai Hospital, NY",18,119,67,0.563025,1852,166,1
18,"NYU Langone Medical Center, NY",19,32998,14481,0.438845,1841,177,1
19,Mayo clinic Phoenix,20,32232,18245,0.566052,1988,30,1

### Check if two variables are normally distributed

In [9]:
row_name =['Retweets to Likes', 'Affiliation']
for i in row_name:
    x = stats.shapiro(data[i])
    print('The test statistics and p-value for', i, 'is' , x)

# return (t-stat, p-value)
# Null: data is normal.
# If it's less than .05, not normal.

# Retweets to Likes is not normally distributed but affiliation types is normally distributed.

The test statistics and p-value for Retweets to Likes is (0.8528748750686646, 0.005957822315394878)
The test statistics and p-value for Affiliation is (0.6309834718704224, 6.2740050452703144e-06)

### One-way ANOVA

In [25]:
private = [x for x in data['Retweets to Likes'][data['Affiliation'] == 1]]
public = [x for x in data['Retweets to Likes'][data['Affiliation'] == 2]]
mixed = [x for x in data['Retweets to Likes'][data['Affiliation'] == 3]]
stats.f_oneway(private, public, mixed) 
# No relation between affiliation types (private vs public vs mixed) and Twitter likability index

F_onewayResult(statistic=2.2061851620509465, pvalue=0.14065834140652056)

### Independent t-test

In [38]:
public_mixed = public + mixed
stats.ttest_ind(private, public_mixed) 
# No relation between affiliation types (private vs public + mixed) and Twitter likability index

Ttest_indResult(statistic=1.975986166412474, pvalue=0.06368868492971334)